name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby & Rust
        uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cargo-cache: true
          rubygems: '3.4.10'
      - name: Run the default task
        run: bundle exec rake
